#!/bin/bash
bubble() {
	local arr=("$@")
	local n=${#arr[@]}
	for ((i=0; i < n-1 ; i++)); do
		for((j=0; j < n-i-1; j++)); do
			if [[ ${arr[j]} -gt ${arr[j+1]} ]]; then
				temp=${arr[j]}
				arr[j]=${arr[j+1]}
				arr[j+1]=$temp;
			fi
		done
	done
		
	echo " ${arr[@]}"	

}
myarray=(2 1 4 3)
sortedarray=($(bubble "${myarray[@]}"))
echo "original array: ${myarray[@]}"
echo "sorted array : ${sortedarray[@]}"
